export const mockProjects = [
	{
		id: 1,
		name: "Tets Project 1",
		workspaceName: "Workspace A",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		date: "05 APRIL 2023",
		members: [
			{ id: 1, avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
			{ id: 2, avatar: "https://randomuser.me/api/portraits/women/44.jpg" },
			{ id: 3, avatar: "https://randomuser.me/api/portraits/men/45.jpg" },
		],
		issues: 14,
		status: "",
		private: false,
		tasks: [
			{
				id: 1,
				column: "tasks",
				title: "Overall UX Process of full product for first version",
				labels: ["UX Design", "UX Research"],
				description: "Overall UX Process of full product for first version",
				comments: 12,
				attachments: 4,
				assigned: [
					{ id: 1, avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
					{ id: 2, avatar: "https://randomuser.me/api/portraits/women/44.jpg" },
				],
			},
			{
				id: 2,
				column: "inprogress",
				title: "Design homepage UI",
				labels: ["UI Design"],
				description: "Design homepage UI for MVP",
				comments: 5,
				attachments: 2,
				assigned: [
					{ id: 3, avatar: "https://randomuser.me/api/portraits/men/45.jpg" },
				],
			},
			{
				id: 3,
				column: "review",
				title: "Review login flow",
				labels: ["Review"],
				description: "Review login flow and security",
				comments: 2,
				attachments: 1,
				assigned: [
					{ id: 2, avatar: "https://randomuser.me/api/portraits/women/44.jpg" },
				],
			},
			{
				id: 4,
				column: "done",
				title: "Setup project repo",
				labels: ["Setup"],
				description: "Setup project repository and CI/CD",
				comments: 0,
				attachments: 0,
				assigned: [
					{ id: 1, avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
				],
			},
		],
	},
	{
		id: 2,
		name: "Getting Started App",
		workspaceName: "Workspace B",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		date: "05 APRIL 2023",
		members: [
			{ id: 1, avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
			{ id: 2, avatar: "https://randomuser.me/api/portraits/women/44.jpg" },
			{ id: 3, avatar: "https://randomuser.me/api/portraits/men/45.jpg" },
		],
		issues: 14,
		status: "Private",
		private: true,
		tasks: [
			{
				id: 1,
				column: "tasks",
				title: "Setup onboarding flow",
				labels: ["Onboarding"],
				description: "Setup onboarding flow for new users",
				comments: 3,
				attachments: 1,
				assigned: [
					{ id: 2, avatar: "https://randomuser.me/api/portraits/women/44.jpg" },
				],
			},
			{
				id: 2,
				column: "done",
				title: "Deploy first version",
				labels: ["Deploy"],
				description: "Deploy first version to production",
				comments: 0,
				attachments: 0,
				assigned: [
					{ id: 1, avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
				],
			},
		],
	},
	{
		id: 3,
		name: "Applying for AI Jobs",
		workspaceName: "Workspace C",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		date: "05 APRIL 2023",
		members: [
			{ id: 1, avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
			{ id: 2, avatar: "https://randomuser.me/api/portraits/women/44.jpg" },
			{ id: 3, avatar: "https://randomuser.me/api/portraits/men/45.jpg" },
		],
		issues: 14,
		status: "Offtrack",
		private: false,
		tasks: [
			{
				id: 1,
				column: "tasks",
				title: "Update resume and cover letter",
				labels: ["Resume", "Job Application"],
				description: "Update resume and cover letter for AI jobs",
				comments: 4,
				attachments: 2,
				assigned: [
					{ id: 1, avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
				],
			},
			{
				id: 2,
				column: "inprogress",
				title: "Build AI project portfolio",
				labels: ["AI", "Portfolio"],
				description: "Build portfolio with AI projects",
				comments: 7,
				attachments: 3,
				assigned: [
					{ id: 2, avatar: "https://randomuser.me/api/portraits/women/44.jpg" },
				],
			},
			{
				id: 3,
				column: "review",
				title: "Get feedback on portfolio",
				labels: ["Feedback", "Portfolio"],
				description: "Get feedback on AI portfolio from peers",
				comments: 1,
				attachments: 1,
				assigned: [
					{ id: 3, avatar: "https://randomuser.me/api/portraits/men/45.jpg" },
				],
			},
			{
				id: 4,
				column: "done",
				title: "Apply to AI jobs",
				labels: ["Job Application"],
				description: "Submit applications to AI jobs",
				comments: 0,
				attachments: 0,
				assigned: [
					{ id: 1, avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
				],
			},
		],
	},
	{
		id: 4,
		name: "Better Design System",
		workspaceName: "Workspace D",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		date: "05 APRIL 2023",
		members: [
			{ id: 1, avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
			{ id: 2, avatar: "https://randomuser.me/api/portraits/women/44.jpg" },
			{ id: 3, avatar: "https://randomuser.me/api/portraits/men/45.jpg" },
		],
		issues: 14,
		status: "Offtrack",
		private: false,
		tasks: [
			{
				id: 1,
				column: "tasks",
				title: "Research design systems",
				labels: ["Research", "Design System"],
				description: "Research and gather design systems for reference",
				comments: 6,
				attachments: 2,
				assigned: [
					{ id: 1, avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
				],
			},
			{
				id: 2,
				column: "inprogress",
				title: "Create design system structure",
				labels: ["Design System", "Setup"],
				description: "Create the structure for the design system",
				comments: 3,
				attachments: 1,
				assigned: [
					{ id: 2, avatar: "https://randomuser.me/api/portraits/women/44.jpg" },
				],
			},
			{
				id: 3,
				column: "review",
				title: "Review design system components",
				labels: ["Review", "Design System"],
				description: "Review and finalize design system components",
				comments: 2,
				attachments: 1,
				assigned: [
					{ id: 3, avatar: "https://randomuser.me/api/portraits/men/45.jpg" },
				],
			},
			{
				id: 4,
				column: "done",
				title: "Document design system guidelines",
				labels: ["Documentation", "Design System"],
				description: "Document guidelines for using the design system",
				comments: 0,
				attachments: 0,
				assigned: [
					{ id: 1, avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
				],
			},
		],
	},
	{
		id: 5,
		name: "Better Design System",
		workspaceName: "Workspace E",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		date: "05 APRIL 2023",
		members: [
			{ id: 1, avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
			{ id: 2, avatar: "https://randomuser.me/api/portraits/women/44.jpg" },
			{ id: 3, avatar: "https://randomuser.me/api/portraits/men/45.jpg" },
		],
		issues: 14,
		status: "Offtrack",
		private: false,
		tasks: [
			{
				id: 1,
				column: "tasks",
				title: "Audit current design assets",
				labels: ["Audit", "Design System"],
				description: "Audit current design assets and identify gaps",
				comments: 5,
				attachments: 2,
				assigned: [
					{ id: 1, avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
				],
			},
			{
				id: 2,
				column: "inprogress",
				title: "Develop new design assets",
				labels: ["Design", "Development"],
				description: "Develop new design assets based on the audit",
				comments: 4,
				attachments: 1,
				assigned: [
					{ id: 2, avatar: "https://randomuser.me/api/portraits/women/44.jpg" },
				],
			},
			{
				id: 3,
				column: "review",
				title: "Finalize design assets",
				labels: ["Review", "Design"],
				description: "Finalize design assets and prepare for handoff",
				comments: 2,
				attachments: 1,
				assigned: [
					{ id: 3, avatar: "https://randomuser.me/api/portraits/men/45.jpg" },
				],
			},
			{
				id: 4,
				column: "done",
				title: "Handoff design assets to development",
				labels: ["Handoff", "Design"],
				description: "Handoff design assets to development team",
				comments: 0,
				attachments: 0,
				assigned: [
					{ id: 1, avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
				],
			},
		],
	},
	{
		id: 6,
		name: "Better Design System",
		workspaceName: "Workspace F",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		date: "05 APRIL 2023",
		members: [
			{ id: 1, avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
			{ id: 2, avatar: "https://randomuser.me/api/portraits/women/44.jpg" },
			{ id: 3, avatar: "https://randomuser.me/api/portraits/men/45.jpg" },
		],
		issues: 14,
		status: "Offtrack",
		private: false,
		tasks: [
			{
				id: 1,
				column: "tasks",
				title: "Gather feedback on design system",
				labels: ["Feedback", "Design System"],
				description: "Gather feedback on the design system from users",
				comments: 3,
				attachments: 1,
				assigned: [
					{ id: 2, avatar: "https://randomuser.me/api/portraits/women/44.jpg" },
				],
			},
			{
				id: 2,
				column: "done",
				title: "Iterate on design system",
				labels: ["Iteration", "Design System"],
				description: "Iterate on the design system based on feedback",
				comments: 0,
				attachments: 0,
				assigned: [
					{ id: 1, avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
				],
			},
		],
	},
	{
		id: 7,
		name: "Better Design System",
		workspaceName: "Workspace G",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		date: "05 APRIL 2023",
		members: [
			{ id: 1, avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
			{ id: 2, avatar: "https://randomuser.me/api/portraits/women/44.jpg" },
			{ id: 3, avatar: "https://randomuser.me/api/portraits/men/45.jpg" },
		],
		issues: 14,
		status: "Offtrack",
		private: false,
		tasks: [
			{
				id: 1,
				column: "tasks",
				title: "Create design system documentation",
				labels: ["Documentation", "Design System"],
				description: "Create comprehensive documentation for the design system",
				comments: 6,
				attachments: 2,
				assigned: [
					{ id: 1, avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
				],
			},
			{
				id: 2,
				column: "inprogress",
				title: "Develop design system components",
				labels: ["Development", "Design System"],
				description: "Develop components for the design system",
				comments: 4,
				attachments: 1,
				assigned: [
					{ id: 2, avatar: "https://randomuser.me/api/portraits/women/44.jpg" },
				],
			},
			{
				id: 3,
				column: "review",
				title: "Review and test design system",
				labels: ["Review", "Testing"],
				description: "Review and test the design system components",
				comments: 2,
				attachments: 1,
				assigned: [
					{ id: 3, avatar: "https://randomuser.me/api/portraits/men/45.jpg" },
				],
			},
			{
				id: 4,
				column: "done",
				title: "Launch design system",
				labels: ["Launch", "Design System"],
				description: "Launch the design system for internal use",
				comments: 0,
				attachments: 0,
				assigned: [
					{ id: 1, avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
				],
			},
		],
	},
];